# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliTools < Formula
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.2.0"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.2.0/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "95e2c2def31ce8610fe93fcebb675154deb3d996ddbb126ca9ef80d133bda12a"

      def install
        bin.install "date-photos"
        bin.install "remove-duplicate-photos"
        bin.install "remove-files"
      end
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.2.0/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "0eb17387f7962cf6c90db50024d340a1d48aca73743ed31884705c8df20622b2"

      def install
        bin.install "date-photos"
        bin.install "remove-duplicate-photos"
        bin.install "remove-files"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.2.0/homebrew-tools_Linux_x86_64.tar.gz"
        sha256 "9f0bb1a306ee50d2e8b59f5eb6e8eb19e8f791dd8c164bb88eebc95103913416"

        def install
          bin.install "date-photos"
          bin.install "remove-duplicate-photos"
          bin.install "remove-files"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.2.0/homebrew-tools_Linux_arm64.tar.gz"
        sha256 "9734b2fe1c1548a9e1c9376d7da548e7965d5079433c3c2f4027ec891aace69d"

        def install
          bin.install "date-photos"
          bin.install "remove-duplicate-photos"
          bin.install "remove-files"
        end
      end
    end
  end
end
