# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCliTools < Formula
  desc ""
  homepage "https://github.com/Caspian-X/homebrew-tools"
  version "1.1.0"

  on_macos do
    on_intel do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Darwin_x86_64.tar.gz"
      sha256 "daae24e7ef0fb07e90f1d975eb70bae00e6f31e4541579dbce48df5a8d2bd175"

      def install
        bin.install "date-screenshots"
        bin.install "remove-duplicate-photos"
      end
    end
    on_arm do
      url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Darwin_arm64.tar.gz"
      sha256 "77ab62477757fb31384c0519a20c83642704f2bafdb811b6725f5a6bf93aa06a"

      def install
        bin.install "date-screenshots"
        bin.install "remove-duplicate-photos"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Linux_x86_64.tar.gz"
        sha256 "a2e8bead788032ea66e154b2fd9889c4a0a4eb815ae57308a7766b724c63b3c7"

        def install
          bin.install "date-screenshots"
          bin.install "remove-duplicate-photos"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Caspian-X/homebrew-tools/releases/download/v1.1.0/homebrew-tools_Linux_arm64.tar.gz"
        sha256 "98af89309741e0577cfeae9bcd1978abfcf0482735acbd5705a8cb9269289aa7"

        def install
          bin.install "date-screenshots"
          bin.install "remove-duplicate-photos"
        end
      end
    end
  end
end
